motores = [
    {
        'id': 1,
        'nome': 'Motor à prova de explosão',
        'descricao': 'Bombas, centrais de ar condicionado, ventiladores, britadores, talhas, compressores, transportadores contínuos, máquinas operatrizes, bobinadeiras, moinhos, trefiladeiras, centrífugas, prensas, guindastes, pontes rolantes, cavalos mecânicos para prospecção de petróleo, elevadores, teares, trituradores, picadores de madeira, injetores, mesas de rolos, torres de resfriamento,embaladeiras e onde houver presença de produtos inflamáveis, com áreas classificadas como Zona 1 (ABNT/IEC).',
        'caracteristicas': [
            '<li>Proteção: IP55;</li>',
            '<li>Vedação nos mancais: retentor (90S a 315, II Pólos);</li>',
            '<li>Carcaça: Ferro fundido labirinto taconite (315 IV, VI, VIII pólos a 355);</li>',
            '<li>Potência: 0,5 a 500cv (carcaças 90S a 355M/L);</li>',
            '<li>Termostato;</li>',
            '<li>Classe de isolamento “F” (ΔT 80● C);</li>',
            '<li>Fator de Serviço: 1.00;</li>',
            '<li>Tensões: 220/380V, 380/660V (carcaças 90S a 200L); 220/380/440V (carcaças 225S/M a 355M/L);</li>',
            '<li>Cor: Azul RAL 5007;</li>',
            '<li>Anel de fixação interno em ambas as tampas, para impedir a propagação das chamas;</li>',
            '<li>Placa de identificação contendo: normas, áreas classificadas, categoria de temperatura, número do certificado de conformidade.</li>'
        ],
        'img_url': '/static/img/motores/motor-a-prova-de-explosao.jpg'
    },
    {
        'id': 2,
        'nome': 'Motofreio à prova de explosão',
        'descricao': 'A linha Motofreio à prova de explosão foi especialmente desenvolvida para aplicações em áreas de risco que precisem de frenagem, como talhas e pontes rolantes. Estes motores estão aptos a trabalhar em áreas classificadas tanto como Zona 1 quanto Zona 2, Grupo IIA/IIB, T4.',
        'caracteristicas': [
            '<li>Alto Rendimento Plus;</li>',
            '<li>Grau de proteção: IP66W;</li>',
            '<li>Potências: 0,33 a 50 cv (carcaças 90S a 200L);</li>',
            '<li>Frequência: 60 Hz;</li>',
            '<li>Tensão: 440 V;</li>',
            '<li>Apto a operar com inversor de frequência;</li>',
            '<li>Vedação dos mancais: Retentor com mola (Carcaças 90S a 112M); Labirinto W3Seal® Carcaças 132S a 200L);</li>',
            '<li>Carcaças em ferro fundido;</li>',
            '<li>Classe de isolamento “F” (ΔT 80● C);</li>',
            '<li>Sistema de isolação WISE® (WEG Insulation System Evolution);</li>',
            '<li>Fator de serviço 1,15;</li>',
            '<li>Proteção térmica PTC 130;</li>',
            '<li>Apto a trabalhar em Zona 1 e Zona 2;</li>',
            '<li>Placa de Bornes;</li>',
            '<li>Certificação UC / Brasil;</li>',
            '<li>Cor:  Verde 6002</li>',
            '<li>Plano de pintura WEG 203A.</li>'
        ],
        'img_url': '/static/img/motores/motor-freio-a-prova-de-explosao.jpg'
    },
    {
        'id': 3,
        'nome': 'Moto Freio para redutor tipo 1',
        'descricao': 'Especialmente desenvolvida para a aplicação em redutores de velocidade, a linha de Motofreios para redutor tipo 1 WEG é indicada para aplicações onde são exigidas paradas rápidas, posicionamento, economia de tempo e segurança como: talhas, pontes rolantes, elevadores, polias automáticas, guinchos e diversas máquinas operatrizes de uso geral.',
        'caracteristicas': [
            '<li>Também disponível em Alto Rendimento Plus;</li>',
            '<li>Freio especial INTORQ (Maior conjugado frenagem)</li>',
            '<li>Grau de proteção: IP55;</li>',
            '<li>Vedação especial: Oil Seal – retentor com mola (dianteiro) e retentor sem molas (traseiro);</li>',
            '<li>Carcaças em ferro fundido;</li>',
            '<li>Bujão para dreno de óleo;</li>',
            '<li>Anel de centrifugação de óleo;</li>',
            '<li>Potências: 0,16 a 15 cv (carcaças 63 a 132M)</li>',
            '<li>Classe de isolamento “F” (ΔT 80°C);</li>',
            '<li>Fator de Serviço: 1,15;</li>',
            '<li>Rolamento de esferas;</li>',
            '<li>Categoria N;</li>',
            '<li>Tensões: 220/380 V, 380/660 V ou 220/380/440 V;</li>',
            '<li>Cor: Azul RAL 5007;</li>',
            '<li>Apto a operar com inversor de frequência;</li>'
        ],
        'img_url': '/static/img/motores/motor-freio-redutor-tipo-1.jpg'
    },
    {
        'id': 4,
        'nome': 'Moto Freio alto rendimento plus',
        'descricao': 'O Motofreio WEG atende as seguintes aplicações: elevadores de carga, talhas, máquinas-ferramentas, teares, máquinas de embalagem, transportadores, máquinas de lavar e engarrafar, dobradeiras, enfim, em equipamentos onde são exigidas paradas rápidas por questões de segurança, posicionamento e economia de tempo.',
        'caracteristicas': [
            '<li>Alto Rendimento Plus;</li>',
            '<li>Grau de Proteção: IP55;</li>',
            '<li>Vedação de mancais: V’Ring dianteiro e retentor traseiro;</li>',
            '<li>Carcaça em ferro fundido;</li>',
            '<li>Dreno automático;</li>',
            '<li>Potências: 0,16 a 50 cv (carcaças 71 a 200L);</li>',
            '<li>Classe de isolamento “F” (ΔT 80°C);</li>',
            '<li>Fator de serviço: 1,15;</li>',
            '<li>Categoria: N;</li>',
            '<li>Tensões: 220/380 V;</li>',
            '<li>Alimentação freio: 220 V;</li>',
            '<li>Freio com pastilhas (carcaças 71 a 160L);</li>',
            '<li>Freio com lona (180M a 200L);</li>',
            '<li>Cor: Verde RAL 6002;</li>',
            '<li>Apto a operar com inversor de frequência;</li>'
        ],
        'img_url': '/static/img/motores/motor-freio-alto-rendimento.jpg'
    },
    {
        'id': 5,
        'nome': 'W22 Premium',
        'descricao': 'Os motores W22 Premium são motores de altíssima eficiência e possuem o maior nível de rendimento do mercado, superando o W22 Plus e o Alto Rendimento Plus, excedendo os níveis de rendimento definidos na portaria 553 da lei de eficiência energética 10.295, em vigor desde janeiro de 2010.',
        'caracteristicas': [
            '<li>Rendimento Premium – em conformidade com a nova lei de eficiência energética, em vigor desde janeiro de 2010;</li>',
            '<li>Grau de proteção: IP55 carcaças 63 a 200M; IP55W a partir da carcaça 225S/M;</li>',
            '<li>Potência: 0,16 a 750 cv;</li>',
            '<li>Carcaças: 63 a 355A/B;</li>',
            '<li>Polaridade: 2, 4, 6 e 8 pólos;</li>',
            '<li>Tensão: 220/380/440 V com 12 cabos;</li>',
            '<li>Flexibilidade da posição da caixa de ligação acima da carcaça 225S/M (B3D, B3E e B3T);</li>',
            '<li>Defletora de chapa carcaças 63 a132M/L;</li>',
            '<li>Defletora em ferro fundido a partir da carcaça 160M;</li>',
            '<li>Grau de vibração A, de acordo com a NBR / IEC 34-14;</li>',
            '<li>Sistema de vedação V’ring carcaças 63 a 200M e WSeal® (exclusivo WEG); a partir da carcaça 225S/M;</li>',
            '<li>Sistema de isolação WISE® (WEG Insulation System Evolution) – Apto a operar com inversores de frequência;</li>',
            '<li>Classe de isolamento “F” (ΔT 80 K);</li>',
            '<li>Dois pontos de aterramento na carcaça;</li>',
            '<li>Fator de serviço: 1,25;</li>',
            '<li>Plano de pintura: 203A;</li>',
            '<li>Cor: Verde RAL 6002</li>'
        ],
        'img_url': '/static/img/motores/w22-premium.jpg'
    },
    {
        'id': 6,
        'nome': 'W22 Plus',
        'descricao': 'Os motores W22 Plus são motores de alta eficiência e possuem nível de rendimento similar ao Alto Rendimento Plus excedendo os níveis de rendimento definidos na portaria 553 da lei de eficiência energética 10.295, que está em vigor desde janeiro de 2010.',
        'caracteristicas': [
            '<li>Rendimento Plus – em conformidade com a nova lei de eficiência energética, em vigor desde janeiro de 2010;</li>',
            '<li>Grau de proteção: IP55 carcaças 63 a 200M; IP55W a partir da carcaça 225S/M;</li>',
            '<li>Potência: 0,16 a 750 cv;</li>',
            '<li>Carcaças: 63 a 355A/B;</li>',
            '<li>Polaridade: 2, 4, 6 e 8 pólos;</li>',
            '<li>Tensão: 220/380/440 V com 12 cabos;</li>',
            '<li>Flexibilidade da posição da caixa de ligação acima da carcaça 225S/M (B3D, B3E e B3T);</li>',
            '<li>Defletora de chapa carcaças 63 a132M/L;</li>',
            '<li>Defletora em ferro fundido a partir da carcaça 160M;</li>',
            '<li>Grau de vibração A, de acordo com a NBR / IEC 34-14;</li>',
            '<li>Sistema de vedação V’ring carcaças 63 a 200M e WSeal® (exclusivo WEG); a partir da carcaça 225S/M;</li>',
            '<li>Sistema de isolação WISE® (WEG Insulation System Evolution) – Apto a operar com inversores de frequência;</li>',
            '<li>Classe de isolamento “F” (ΔT 80 K);</li>',
            '<li>Dois pontos de aterramento na carcaça;</li>',
            '<li>Fator de serviço: 1,15;</li>',
            '<li>Plano de pintura: 203A;</li>',
            '<li>Cor: Azul RAL 5009.</li>'
        ],
        'img_url': '/static/img/motores/w22-plus.jpg'
    },
    {
        'id': 7,
        'nome': 'W21 Carcaça de Alumínio – Montagem',
        'descricao': 'Os motores carcaça de alumínio WEG com base removível foram desenvolvidos especialmente para atender aplicações como: bombas, centrais de ar condicionado, ventiladores, talhas, compressores, transportadores contínuos, máquinas operatrizes, bobinadeiras, trefiladeiras, centrífugas, prensas, guindastes, pontes rolantes, elevadores, teares, trituradores, picadores, de madeira, injetoras, extrusoras, mesa de rolos, torres de resfriamento, embaladeiras e outras necessidades do mercado pois têm a flexibilidade de permitir todas as posições de montagens.',
        'caracteristicas': [
            '<li>Também disponível em Alto Rendimento Plus;</li>',
            '<li>Potência: 0,16 a 15 cv (0,12 a 11 kW)</li>',
            '<li>Pólos: II, IV, VI e VIII</li>',
            '<li>Carcaça (63 a 132M)</li>',
            '<li>Baixa tensão</li>',
            '<li>Freqüência: 60 ou 50Hz</li>',
            '<li>Proteção: IP55 (TFVE)</li>',
            '<li>De acordo com a Norma ABNT / IEC</li>',
            '<li>Caixa de ligação no topo</li>'
        ],
        'img_url': '/static/img/motores/w21-carcaca-de-aluminio-montagem.jpg'
    },
    {
        'id': 8,
        'nome': 'W21 Alto Rendimento Plus',
        'descricao': 'O Motor Trifásico Alto Rendimento Plus pode ser aplicado em bombas, ventiladores, exaustores, britadores, moinhos, talhas, compressores e outras aplicações que requerem motores assíncronos de indução trifásicos com o máximo de rendimento e consumo reduzido.',
        'caracteristicas': [
            '<li>Alto Rendimento Plus;</li>',
            '<li>Grau de proteção: IP55;</li>',
            '<li>Vedação nos mancais: V’Ring;</li>',
            '<li>Carcaças: ferro fundido;</li>',
            '<li>Dreno automático;</li>',
            '<li>Potências: 0,16 a 500 cv (carcaças 63 a 355M/L);</li>',
            '<li>Classe de isolamento “F” (ΔT 80°C);</li>',
            '<li>Fator de serviço: 1,15;</li>',
            '<li>Rolamento de esferas (com graxeira a partir da carcaça 225S/M);</li>',
            '<li>Rolamento dianteiro de rolos: carcaças 355M/L – 4, 6 e 8 pólos;</li>',
            '<li>Sistema de isolamento WISE;</li>',
            '<li>Categoria: N;</li>',
            '<li>Tensões: 220/380 V, 380/660 V (carcaças 63 a 200L), 220/380/440 V (carcaças 225S/M a 355M/L);</li>',
            '<li>Apto a operar com inversor de frequência;</li>',
            '<li>Cor: Verde Ral 6002;</li>'
        ],
        'img_url': '/static/img/motores/w21-alto-rendimento-plus-1.jpg'
    },
    {
        'id': 9,
        'nome': 'W21 Motor Trifásico IP55',
        'descricao': 'O Motor Trifásico IP55 pode ser aplicado em bombas, ventiladores, exaustores, britadores, moinhos, talhas, compressores e outras aplicações que requerem motores assíncronos de indução trifásicos.',
        'caracteristicas': [
            '<li>Grau de proteção: IP55;</li>',
            '<li>Vedação dos mancais: V’Ring;</li>',
            '<li>Carcaças: ferro fundido;</li>',
            '<li>Dreno automático;</li>',
            '<li>Potências: 0,16 a 500 cv (carcaças 63 a 355M/L);</li>',
            '<li>Classe de Isolamento “F” (ΔT 80 °C);</li>',
            '<li>Fator de serviço: 1,15 (carcaças 63 a 200L), 1,00 (carcaças 225S/M a 355M/L);</li>',
            '<li>Rolamentos de esferas (com graxeira a partir da carcaça 225S/M);</li>',
            '<li>Rolamento dianteiro de rolos: carcaças 355M/L – 4, 6 e 8 pólos;</li>',
            '<li>Forma construtiva B3D;</li>',
            '<li>Sistema de isolamento WISE;</li>',
            '<li>Categoria: N;</li>',
            '<li>Apto a operar com inversor de freqüência</li>',
            '<li>Cor: Azul RAL 5007;</li>'
        ],
        'img_url': '/static/img/motores/motor-w21-aluminio-multimontagem-weg.jpg'
    }
]